### PR TITLE
Toolchain: Added build script

### PR DESCRIPTION
**Pull request by NicolasVanBossuyt**
When finish this should be able to download, patch and build the serenity toolchain automagicaly 🧙‍♂️

### CODE REVIEW

**Comment by NicolasVanBossuyt** [comment]
Still working on it i'm just busy with University and stuff 😉

**Comment by NicolasVanBossuyt** [comment]
Use `./Toolchain/BuildIt.sh` to build the cross compiler
and `./Toolchain/UseIt.sh` to add it to your path :^)

**Comment by awesomekling** [comment]
Excellent! Could you rebase the commits on top of current master and get rid of the conflicts, then I can review and merge :)

**Comment by NicolasVanBossuyt** [comment]
It took me two tries, but I managed to do it 😅

**Comment by awesomekling** [comment]
Hi Nicolas! Sorry about the delay, I mistakenly thought there were still merge conflicts in this PR but I see that it's actually clean :)

The scripts look really nice, thank you for making them! Merging. :+1:

**Pull request merged**
