### PR TITLE
Meta: making the readme all pretty :)

### PR DESCRIPTION
**Pull request by NicolasVanBossuyt**
I come across this little girl in the repository, maybe she can have a nice place in the readme :)

*serenity.png*

What this look like: https://github.com/NicolasVanBossuyt/serenity

### CODE REVIEW

**Comment by awesomekling** [comment]
Hmm, I think we need to get rid of this icon actually. It's a clip art icon that I got from somewhere to use as a placeholder for system logo in the "About" app and then forgot about it. I don't have the copyright for it, sadly :(

**Comment by awesomekling** [comment]
Okay, I replaced the ladybug with something I drew myself to avoid copyright issues.
I think this patch is okay, but I don't know why we need a link to "Releases" since there are no releases :)

**Comment by NicolasVanBossuyt** [comment]
I know but i needed a third link for visual balance 😅

**Comment by awesomekling** [comment]
Let's skip this, I think the ReadMe is fine the way it is. I appreciate the effort though :)

**Pull request closed without merging**
